export const SAFETY_ERROR_CODES = {
  SAFETY_CONTACT_LIMIT_REACHED: "SAFETY_CONTACT_LIMIT_REACHED",
  SAFETY_CONTACT_NOT_FOUND: "SAFETY_CONTACT_NOT_FOUND",
  SAFETY_INCIDENT_NOT_FOUND: "SAFETY_INCIDENT_NOT_FOUND",
  SAFETY_NO_ACTIVE_TRIP: "SAFETY_NO_ACTIVE_TRIP",
  SAFETY_SOS_ALREADY_ACTIVE: "SAFETY_SOS_ALREADY_ACTIVE",
  SAFETY_SHARE_NOT_FOUND: "SAFETY_SHARE_NOT_FOUND",
  SAFETY_SHARE_EXPIRED: "SAFETY_SHARE_EXPIRED",
  SAFETY_SHARE_ALREADY_ACTIVE: "SAFETY_SHARE_ALREADY_ACTIVE",
  SAFETY_INVALID_TRIP: "SAFETY_INVALID_TRIP",
  SAFETY_EVIDENCE_TOO_LARGE: "SAFETY_EVIDENCE_TOO_LARGE",
  SAFETY_EVIDENCE_INVALID_TYPE: "SAFETY_EVIDENCE_INVALID_TYPE",
  SAFETY_CHECK_IN_NOT_FOUND: "SAFETY_CHECK_IN_NOT_FOUND",
  SAFETY_CHECK_IN_ALREADY_RESOLVED: "SAFETY_CHECK_IN_ALREADY_RESOLVED",
} as const;

export type SafetyErrorCode =
  (typeof SAFETY_ERROR_CODES)[keyof typeof SAFETY_ERROR_CODES];

export const SAFETY_ERROR_HTTP_STATUS: Record<SafetyErrorCode, number> = {
  SAFETY_CONTACT_LIMIT_REACHED: 409,
  SAFETY_CONTACT_NOT_FOUND: 404,
  SAFETY_INCIDENT_NOT_FOUND: 404,
  SAFETY_NO_ACTIVE_TRIP: 422,
  SAFETY_SOS_ALREADY_ACTIVE: 200,
  SAFETY_SHARE_NOT_FOUND: 404,
  SAFETY_SHARE_EXPIRED: 410,
  SAFETY_SHARE_ALREADY_ACTIVE: 200,
  SAFETY_INVALID_TRIP: 422,
  SAFETY_EVIDENCE_TOO_LARGE: 413,
  SAFETY_EVIDENCE_INVALID_TYPE: 422,
  SAFETY_CHECK_IN_NOT_FOUND: 404,
  SAFETY_CHECK_IN_ALREADY_RESOLVED: 409,
};

export function isSafetyErrorCode(code: string): code is SafetyErrorCode {
  return Object.values(SAFETY_ERROR_CODES).includes(code as SafetyErrorCode);
}
